name: amiara-iac-apps
description: Amiara Infrastructure as Code for GKE and Redis
runtime:
  name: nodejs
  options:
    typescript: false
    packagemanager: pnpm
config:
  pulumi:tags:
    value:
      pulumi:template: gcp-javascript
